import Footer from '@/components/common/Footer';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Will You',
    description: 'Generated by create next app',
};

export default function UserLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <main>
                    {children}
                </main>
                {/* <Footer /> */}
            </body>
        </html>
    );
}
